# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee67f9b3437ba3d0da19caf14ba94fd83c0432b93ffba77624ea7b3d3df6c8585b69d82a13a39c322b20373024deff4ad13c6dd71eb7c203f586c9b42da0966e

test:
  secret_key_base: 4c0264a5cb88b79b7585503bde2c4639ec1aa629500bdd17611adf888243b6bc7f11958920a54ec995a411271e119ac160cd036af864c01f92ffb7c5a6730be5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
